#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<Olive.Website.ViewModels.Account.EditViewModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
  
    ViewBag.Title = "Edit";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Edit account #");


            
            #line 7 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
             Write(Model.AccountId);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<p>Introduction.</p>\r\n\r\n");


            
            #line 10 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
 using (Html.BeginRouteForm("Account/Edit", new { accountId = @Model.AccountId }))
{ 

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 13 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
   Write(Html.LabelFor(m => m.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 14 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
   Write(Html.TextBoxFor(m => m.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 15 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
   Write(Html.ValidationMessageFor(m => m.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 17 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <input type=\"submit\" value=\"Save changes\" />\r\n");



WriteLiteral("    <a href=\"/Account\">Cancel</a>\r\n");


            
            #line 20 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
