// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Edit.cs" company="Olive">
//   
// </copyright>
// <summary>
//   Defines the Edit type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.Account
{
    using System.Web.Mvc.Html;

    using Olive.Website.ViewModels.Account;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Edit.cshtml")]
    public class Edit : System.Web.Mvc.WebViewPage<EditViewModel>
    {
        public override void Execute()
        {
            this.WriteLiteral("\r\n");

#line 3 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"

            this.ViewBag.Title = "Edit";

#line default
#line hidden
            this.WriteLiteral("\r\n<h2>Edit account #");

#line 7 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
            this.Write(this.Model.AccountId);

#line default
#line hidden
            this.WriteLiteral("</h2>\r\n<p>Introduction.</p>\r\n\r\n");

#line 10 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
            using (this.Html.BeginForm())
            {
#line default
#line hidden

#line 12 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
                this.Write(this.Html.DisplayFor(m => m));

#line default
#line hidden

#line 12 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"

#line default
#line hidden
                this.WriteLiteral("    <input type=\"submit\" value=\"Edit\" />\r\n");

#line 15 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\Account\Edit.cshtml"
            }

#line default
#line hidden
        }
    }
}

#pragma warning restore 1591