CREATE PROCEDURE [Banking].[ReleaseAccountHold]
	@AccountHoldId INT

AS

DECLARE @TC INT = @@TRANCOUNT
IF @TC = 0 BEGIN TRAN
ELSE SAVE TRAN TR1

BEGIN TRY
	IF @AccountHoldId IS NULL RAISERROR(51003, 16, 1, '@AccountHoldId');

	DELETE FROM Banking.AccountHold WHERE AccountHoldId = @AccountHoldId;

	IF @@ROWCOUNT = 0
		RAISERROR(51014, 16, 1);

	IF @TC = 0 COMMIT TRAN

	RETURN 0
END TRY
BEGIN CATCH
	IF @TC = 0 ROLLBACK TRAN;
	ELSE ROLLBACK TRAN TR1;

	SELECT ERROR_NUMBER();

	RETURN ERROR_NUMBER()
END CATCH
