ALTER TABLE [dbo].[Currency]
    ADD CONSTRAINT [PK_Currency] PRIMARY KEY CLUSTERED ([CurrencyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

