ALTER TABLE [Banking].[AccountUser]
    ADD CONSTRAINT [PK_AccountUser] PRIMARY KEY CLUSTERED ([AccountId] ASC, [UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

