#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
    using Olive.Website.Views;
    
    #line default
    #line hidden
    
    #line 3 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
    using Olive.Website.Views.Account;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Create.cshtml")]
    public class Create : System.Web.Mvc.WebViewPage<Olive.Website.ViewModels.Account.CreateViewModel>
    {
        public Create()
        {
        }
        public override void Execute()
        {




            
            #line 4 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
  
    ViewBag.Title = AccountResources.Create_DocumentTitle;


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");


            
            #line 8 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
Write(AccountResources.Create_PageHeading);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");


            
            #line 10 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
 using (Html.BeginForm()) 
{
   
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
Write(Html.ValidationSummary(true, ViewResources.DefaultValidationSummary));

            
            #line default
            #line hidden
            
            #line 12 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
                                                                        

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <div>\r\n            ");


            
            #line 15 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
       Write(Html.LabelFor(m => m.CurrencyId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 16 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
       Write(Html.DropDownListFor(m => m.CurrencyId, Model.Currencies.Select(c => new SelectListItem { Value = c, Text = c })));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 17 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
       Write(Html.ValidationMessageFor(m => m.CurrencyId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div>\r\n            ");


            
            #line 21 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
       Write(Html.LabelFor(m => m.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 22 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
       Write(Html.TextBoxFor(m => m.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 23 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
       Write(Html.ValidationMessageFor(m => m.DisplayName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div>\r\n            <input type=\"submit\" value=\"");


            
            #line 27 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
                                   Write(AccountResources.Create_SubmitButtonCaption);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        </div>\r\n    </fieldset>\r\n");


            
            #line 30 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Account\Create.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
