#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Details.cshtml")]
    public class Details : System.Web.Mvc.WebViewPage<Olive.Website.ViewModels.Account.DetailsViewModel>
    {
        public Details()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Details.cshtml"
  
    ViewBag.Title = "Details";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Details</h2>\r\n\r\n");


            
            #line 9 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Details.cshtml"
 if (Model.BitcoinReceiveAddress != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        Bitcoin receive address: ");


            
            #line 12 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Details.cshtml"
                            Write(Model.BitcoinReceiveAddress);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 14 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Details.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
