#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Transfer.cshtml")]
    public class Transfer : System.Web.Mvc.WebViewPage<Olive.Website.ViewModels.Account.TransferViewModel>
    {
        public Transfer()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
  
    ViewBag.Title = "Transfer";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 7 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
 using (Html.BeginRouteForm("Account_Transfer", new { sourceAccountId = @Model.SourceAccountId }))
{ 

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 10 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.LabelFor(m => m.SourceAccountId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 11 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.TextBoxFor(m => m.SourceAccountId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 12 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.ValidationMessageFor(m => m.SourceAccountId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 14 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 16 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.LabelFor(m => m.DestAccountId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 17 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.TextBoxFor(m => m.DestAccountId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 18 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.ValidationMessageFor(m => m.DestAccountId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 20 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 22 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.LabelFor(m => m.Amount));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 23 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.TextBoxFor(m => m.Amount));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 24 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.ValidationMessageFor(m => m.Amount));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 26 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 28 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.LabelFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 29 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.TextBoxFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 30 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
   Write(Html.ValidationMessageFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 32 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <input type=\"submit\" value=\"Send transfer\" />\r\n");



WriteLiteral("    <a href=\"/Account\">Cancel</a>\r\n");


            
            #line 35 "C:\Users\Andy\AppData\Local\Git\Olive\Website\Views\Account\Transfer.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
