// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Login.cs" company="Olive">
//   
// </copyright>
// <summary>
//   Defines the Login type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.User
{
    using System.Web.Mvc.Html;

    using Olive.Website.ViewModels.User;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/Login.cshtml")]
    public class Login : System.Web.Mvc.WebViewPage<LoginViewModel>
    {
        public override void Execute()
        {
#line 2 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"

            this.ViewBag.Title = "Login";

#line default
#line hidden
            this.WriteLiteral("<h2>");

#line 5 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
            Write(this.ViewBag.Title);

#line default
#line hidden
            this.WriteLiteral("</h2>\r\n\r\n");

#line 7 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
            this.Write(
                this.Html.ValidationSummary(true, "Login was unsuccessful. Please correct the errors and try again."));

#line default
#line hidden
            this.WriteLiteral("\r\n\r\n<div id=\"login-account\">\r\n");

#line 10 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
            using (this.Html.BeginForm())
            {
#line default
#line hidden
                this.WriteLiteral("       <div>\r\n           <p>\r\n               ");

#line 14 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.LabelFor(m => m.Email));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 15 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.TextBoxFor(m => m.Email));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 16 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.ValidationMessageFor(m => m.Email));

#line default
#line hidden
                this.WriteLiteral("\r\n           </p>\r\n           <p>\r\n               ");

#line 19 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.LabelFor(m => m.Password));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 20 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.PasswordFor(m => m.Password));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 21 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.ValidationMessageFor(m => m.Password));

#line default
#line hidden
                this.WriteLiteral(
                    "\r\n           </p>\r\n           <p>\r\n               <input type=\"submit\" value=\"Log"
                    + " On\" />\r\n           </p>\r\n           <p>\r\n               Please enter your usern"
                    + "ame and password. ");

#line 27 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                this.Write(this.Html.ActionLink("Register", "Register"));

#line default
#line hidden
                this.WriteLiteral(
                    "\r\n               if you don\'t have an account.\r\n           </p>\r\n       </div>\r\n");

#line 31 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
            }

#line default
#line hidden
            this.WriteLiteral("</div>");
        }
    }
}

#pragma warning restore 1591