#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.User
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/Login.cshtml")]
    public class Login : System.Web.Mvc.WebViewPage<Olive.Website.ViewModels.User.LoginViewModel>
    {
        public Login()
        {
        }
        public override void Execute()
        {


            
            #line 2 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
  
   ViewBag.Title = "Login";


            
            #line default
            #line hidden
WriteLiteral("<h2>");


            
            #line 5 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n\r\n");


            
            #line 7 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
Write(Html.ValidationSummary(true, "Login was unsuccessful. Please correct the errors and try again."));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div id=\"login-account\">\r\n");


            
            #line 10 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
    using (Html.BeginForm())
   {

            
            #line default
            #line hidden
WriteLiteral("       <div>\r\n           <p>\r\n               ");


            
            #line 14 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
          Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n               ");


            
            #line 15 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
          Write(Html.TextBoxFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n               ");


            
            #line 16 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
          Write(Html.ValidationMessageFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n           </p>\r\n           <p>\r\n               ");


            
            #line 19 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
          Write(Html.LabelFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n               ");


            
            #line 20 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
          Write(Html.PasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n               ");


            
            #line 21 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
          Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n           </p>\r\n           <p>\r\n               <input type=\"submit\" value=\"Log" +
" On\" />\r\n           </p>\r\n           <p>\r\n               Please enter your usern" +
"ame and password. ");


            
            #line 27 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
                                                   Write(Html.ActionLink("Register", "Register"));

            
            #line default
            #line hidden
WriteLiteral("\r\n               if you don\'t have an account.\r\n           </p>\r\n       </div>\r\n");


            
            #line 31 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Login.cshtml"
   }

            
            #line default
            #line hidden
WriteLiteral("</div>");


        }
    }
}
#pragma warning restore 1591
