// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Register.cs" company="Olive">
//   
// </copyright>
// <summary>
//   Defines the Register type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------


#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.User
{
    using System.Web.Mvc.Html;

    using Olive.Website.ViewModels.User;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/Register.cshtml")]
    public class Register : System.Web.Mvc.WebViewPage<RegisterViewModel>
    {
        public override void Execute()
        {
            this.WriteLiteral("\r\n");

#line 3 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"

            this.ViewBag.Title = "Register";

#line default
#line hidden
            this.WriteLiteral("\r\n<h2>");

#line 7 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
            Write(this.ViewBag.Title);

#line default
#line hidden
            this.WriteLiteral("</h2>\r\n<p>\r\n    Use the form below to become a user. \r\n</p>\r\n\r\n");

#line 12 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
            using (this.Html.BeginForm())
            {
#line default
#line hidden

#line 14 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(
                    this.Html.ValidationSummary(
                        true, "User creation was unsuccessful. Please correct the errors and try again."));

#line default
#line hidden

#line 14 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"

#line default
#line hidden
                this.WriteLiteral(
                    "    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n"
                    + "            <p>\r\n               ");

#line 19 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.LabelFor(m => m.Email));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 20 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.TextBoxFor(m => m.Email));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 21 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.ValidationMessageFor(m => m.Email));

#line default
#line hidden
                this.WriteLiteral("\r\n            </p>\r\n            <p>\r\n               ");

#line 24 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.LabelFor(m => m.Password));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 25 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.PasswordFor(m => m.Password));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 26 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.ValidationMessageFor(m => m.Password));

#line default
#line hidden
                this.WriteLiteral("\r\n            </p>\r\n            <p>\r\n               ");

#line 29 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.LabelFor(m => m.ConfirmPassword));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 30 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.PasswordFor(m => m.ConfirmPassword));

#line default
#line hidden
                this.WriteLiteral("\r\n               ");

#line 31 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
                this.Write(this.Html.ValidationMessageFor(m => m.ConfirmPassword));

#line default
#line hidden
                this.WriteLiteral(
                    "\r\n            </p>\r\n            <p>\r\n                <input type=\"submit\" value=\""
                    + "Register\" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");

#line 38 "C:\Users\Andy\AppData\Local\TFS\Tests\Olive\Website\Views\User\Register.cshtml"
            }

#line default
#line hidden
        }
    }
}

#pragma warning restore 1591