#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olive.Website.Views.Error
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.1.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Error/Error.cshtml")]
    public class Error : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Error()
        {
        }
        public override void Execute()
        {

            
            #line 1 "C:\Users\Andy\AppData\Local\Git\Olive\Olive\Website\Views\Error\Error.cshtml"
  
    ViewBag.Title = "Well, this isn't good.";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Some error</h2>\r\n");


        }
    }
}
#pragma warning restore 1591
